[tool.poetry]
name = "two-turtle-doves"
version = "0.1.0"
description = ""
authors = ["doves"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^6.2.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
